apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nobl9-agent.fullname" . }}
  namespace: {{ template "nobl9-agent.namespace" . }}
  labels:
    {{- include "nobl9-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
       {{- include "nobl9-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.annotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nobl9-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent-container
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.version }}
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.config.clientId }}
            - name: N9_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client_id
                  name: {{ template "nobl9-agent.fullname" . }}
            {{- end }}
            {{- if .Values.config.clientSecret }}
            - name: N9_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client_secret
                  name: {{ template "nobl9-agent.fullname" . }}
            {{- end }}
            - name: N9_INTAKE_URL
              value: {{ .Values.config.intakeUrl | quote  }}
            - name: N9_AUTH_SERVER
              value: {{ .Values.config.authServer | quote  }}
            - name: N9_OKTA_ORG_URL
              value: {{ .Values.config.oktaOrgUrl | quote  }}
            {{- if .Values.config.allowedUrls }}
            - name: N9_ALLOWED_URLS
              value: {{ .Values.config.allowedUrls | quote  }}
            {{- end }}
            {{- with .Values.deployment.extraEnvs }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
