apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nobl9-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "nobl9-agent.chart" . }}
    app.kubernetes.io/name: {{ template "nobl9-agent.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service  | quote  }}
    app.kubernetes.io/instance: {{ .Release.Name  | quote  }}
    app.kubernetes.io/version: {{ .Chart.AppVersion  | quote  }}
type: Opaque
stringData:
  {{- if not .Values.config.clientIdFromSecret }}
  client_id: {{ .Values.config.clientId | quote }}
  {{- end }}
  {{- if not .Values.config.clientSecretFromSecret }}
  client_secret: {{ .Values.config.clientSecret | quote }}
  {{- end }}
  {{- range $key, $value := .Values.deployment.extraSecretEnvs }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
