apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nobl9-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  client_id: {{ .Values.config.client_id | quote }}
  client_secret: {{ .Values.config.client_secret | quote }}
