{{- if or (.Values.config.clientId) (.Values.config.clientSecret) (.Values.secret.extraData) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nobl9-agent.secret.name" . }}
  namespace: {{ template "nobl9-agent.namespace" . }}
  labels:
    {{- include "nobl9-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.clientId }}
  client_id: {{ .Values.config.clientId | quote }}
  {{- end }}
  {{- if .Values.config.clientSecret }}
  client_secret: {{ .Values.config.clientSecret | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secret.extraData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
