deployment:
  image: "nobl9/agent"
  version: "0.43.0"
  pullPolicy: Always
  annotations: {}

resources:
  limits:
    cpu: "1.0"
    memory: "1Gi"
  requests:
    cpu: "0.1"
    memory: "350Mi"

## Apply additional labels
extralabels: {}

## Pod Labels
podLabels: {}

## Some data sources require additional authentification
dataSourceAuthType:

## Some data sources require additional authentification
dataSourceAuthName:

## Some data sources require additional secrets for authentification
dataSourceAuthSecrets:

## Navigate to the Integrations tab in Nobl9 UI to obtain below values
config:
  project: "default"
  organization: ""
  datasourceName: ""
  clientId: ""
  clientSecret: ""

  ## Values below should not be changed while working Nobl9 backend
  intakeUrl: "https://nobl9.com/api/input"
  authServer: "auseg9kiegWKEtJZC416"
  oktaOrgUrl: "https://accounts.nobl9.com"

  ## N9_ALLOWED_URLS is an optional safety parameter that limits the URLs that an Agent is able to query
  ## for metrics. URLs defined in the Nobl9 app are prefix-compared against the N9_ALLOWED_URLS list of
  ## comma separated URLs.
  # allowedUrls:
