deployment:
  image: "nobl9/agent"
  version: "0.49.0-rc1"
  pullPolicy: Always
  annotations: {}

resources:
  limits:
    cpu: "1.0"
    memory: "1Gi"
  requests:
    cpu: "0.1"
    memory: "350Mi"

## Security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 2000

## Authentification method environment variable required by some data sources
dataSourceAuthMethod:
#  AUTH_METHOD: api_token

## Name of the secrets environment variables for authentification required by data source as NAME: key
dataSourceAuthNames:
#  API_TOKEN: instana_api_token

## Secrets for authentification required by data source as key: value
dataSourceAuthSecrets:
#  instana_api_token: abcd1234!@#$

## Navigate to the Integrations tab in Nobl9 UI to obtain below values
config:
  project: "default"
  organization: ""
  datasourceName: ""
  clientId: ""
  clientSecret: ""

  ## Values below should not be changed while working Nobl9 backend
  intakeUrl: "https://nobl9.com/api/input"
  authServer: "auseg9kiegWKEtJZC416"
  oktaOrgUrl: "https://accounts.nobl9.com"

  ## N9_ALLOWED_URLS is an optional safety parameter that limits the URLs that an Agent is able to query
  ## for metrics. URLs defined in the Nobl9 app are prefix-compared against the N9_ALLOWED_URLS list of
  ## comma separated URLs.
  # allowedUrls:

## Apply additional container labels
extraLabels: {}

## Pod Labels
podLabels: {}