deployment:
  # -- Image used by chart
  image: "nobl9/agent"
  # -- Agent version (image tag)
  version: "0.48.0"
  # -- Image Pull Policy
  pullPolicy: Always
  # -- Additional data to be included in deployment as Envs, key-value pair
  extraEnvs:
    # AUTH_METHOD: api_token
  # -- Additional data to be included in Secret and read by deployment as Envs, key-value pair
  extraSecretEnvs:
  #  splunk_observability_access_token: abcd1234!@#$
  # -- Deployment annotations
  annotations: {}
  # -- Additional Labels
  extraLabels: {}

resources:
  requests:
    # -- CPU request
    cpu: "0.1"
    # -- Memory request
    memory: "350Mi"
  limits:
    # -- CPU limit
    cpu: "1.0"
    # -- Memory limit
    memory: "1Gi"

securityContext:
  # -- Grants container a privileged status if set to true
  allowPrivilegeEscalation: false
  # -- ReadOnly file system mode if set to true
  readOnlyRootFilesystem: true
  # -- Runs the container as a root user if set to false
  runAsNonRoot: true
  # -- Runs the container with specified PID
  runAsUser: 2000

config:
  # -- Nobl9 Project name
  project: "default"
  # -- Nobl9 Organization name
  organization: ""
  # -- Nobl9 Data Source name
  datasourceName: ""
  # -- Nobl9 Client ID
  clientId: ""
  # -- The Name of Secret containing Nobl9 Client ID, data field name must equal client_id
  clientIdFromSecret:
  # -- Nobl9 Client secret
  clientSecret: ""
  # -- The Name of Secret containing Nobl9 Client Secret, data field name must equal client_secret
  clientSecretFromSecret:

  # -- Nobl9 API URL
  intakeUrl: "https://nobl9.com/api/input"
  # -- Nobl9 Auth Server ID
  authServer: "auseg9kiegWKEtJZC416"
  # -- Nobl9 Okta Organization URL
  oktaOrgUrl: "https://accounts.nobl9.com"

  # -- N9_ALLOWED_URLS is an optional safety parameter that limits the URLs that an Agent is able to query
  # -- for metrics. URLs defined in the Nobl9 app are prefix-compared against the N9_ALLOWED_URLS list of
  # -- comma separated URLs.
  # allowedUrls:

