# -- Override the Namespace
namespaceOverride:
extraLabels: {}

deployment:
  # -- Image used by chart
  image: nobl9/agent
  # -- Agent version (image tag)
  version: latest
  # -- Image Pull Policy
  pullPolicy: Always
  # -- Additional Envs
  extraEnvs:
  # - name: API_KEY
  #   value: my-api-key
  # - name: splunk_api_token
  #   valueFrom:
  #     secretKeyRef:
  #       key: my-existing-secret-key
  #       name: my-existing-secret
  # - name: N9_CLIENT_ID
  #   valueFrom:
  #     secretKeyRef:
  #       key: client_id
  #       name: my-existing-secret
  # - name: N9_CLIENT_SECRET
  #   valueFrom:
  #     secretKeyRef:
  #       key: client_secret
  #       name: my-existing-secret
  # -- Custom annotations
  annotations: {}
  # -- Additional Labels

secret:
  # -- Override the Secret name
  nameOverride:
  # -- Extra stringData to be included in secret, use deployment.extraEnvs to load as deployment Envs
  extraData:
    # splunk_api_token: my-api-token

resources:
  requests:
    # -- CPU request
    cpu: "0.1"
    # -- Memory request
    memory: "350Mi"
  limits:
    # -- CPU limit
    cpu: "1.0"
    # -- Memory limit
    memory: "1Gi"

securityContext:
  # -- Grants container a privileged status if set to true
  allowPrivilegeEscalation: false
  # -- ReadOnly file system mode if set to true
  readOnlyRootFilesystem: true
  # -- Runs the container as a root user if set to false
  runAsNonRoot: true
  # -- Runs the container with specified PID
  runAsUser: 2000

config:
  # -- Nobl9 Project name
  project:
  # -- Nobl9 Organization name
  organization:
  # -- Nobl9 Data Source name
  datasourceName:
  # -- Nobl9 Client ID, creates secret with this value, leave empty and use deployment.extraEnvs to load from existing Secret
  clientId:
  # -- Nobl9 Client secret, creates secret with this value, leave empty and use deployment.extraEnvs to load from existing Secret
  clientSecret:

  # -- Nobl9 API URL
  intakeUrl: "https://app.nobl9.com/api/input"
  # -- Nobl9 Auth Server ID
  authServer: "auseg9kiegWKEtJZC416"
  # -- Nobl9 Okta Organization URL
  oktaOrgUrl: "https://accounts.nobl9.com"

  # -- Populates N9_ALLOWED_URLS that limits the URLs which an Agent is able to query
  allowedUrls:

