name: Release Charts
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
          linting: off
